baseURL = "https://bartjanboverhof.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Bart-Jan Boverhof"
theme = "soho-master"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Bart-Jan Boverhof"
author = "Bart-Jan"
description = "Statistician"
profilePicture = "images/profile.jpg"
keywords = "Bart-Jan Boverhof, Bart-Jan, Boverhof, Utrecht University, Statistics, Statistiek"
doNotLoadAnimations = false
displayMode = "dark"
themeColor = "#9b9796"
copyright = "Bart-Jan Boverhof"
builtWith = true

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/bart-jan-boverhof-5380a6142"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/BartJanBoverhof"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:bjboverhof@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "About Me"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "CV"
  weight = 400
  identifier = "cv.pdf"
  url = "/cv/cv.pdf"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
