baseURL = "https://bartjanboverhof.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Home"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Bart-Jan Boverhof"
author = "Bart-Jan"
description = "Student Methods & Statistics"
profilePicture = "images/profile.jpg"
keywords = "q"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = []
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
displayMode = "dark"



## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/bart-jan-boverhof-5380a6142"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/BartJanBoverhof"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:bjboverhof@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About Me"
  weight = 300
  identifier = "about"
  url = "/about/about/"

  [[menu.main]]
  name = "CV"
  weight = 400
  identifier = "cv.pdf"
  url = "/cv/cv.pdf"
