baseURL = "https://bartjanboverhof.github.io"
title = "Bart-Jan Boverhof"
theme = "coder-portfolio"


DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

[params]
    author = "Bart-Jan Boverhof"
    description = "Bart-Jan's Personal Website"
    keywords = "developer,personal,boverhof,bart-jan,deeplearning,statistics"
    info = "Statistician & Data Scientist"
    avatarurl = "images/bj.jpg"
    fixedbarContentAfter = "Thank You! Please share it if you like it→"

    hideCredits = false
    hideCopyright = false


   # Bottom sns share
    snsShare = true
    # Popular sns share
    # if you want add sns. please message!


    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"



[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/BartJanBoverhof"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/bart-jan-boverhof-5380a6142"
[[params.social]]
    name = "Mail"
    icon = "fas fa-envelope"
    weight = 3
    url = "mailto:bjboverhof@gmail.com"
[[params.social]]
    name = "Mail"
    icon = "fas fa-book"
    weight = 3
    url = "https://www.goodreads.com/user/show/90941480-bart-jan"
## Menu items

[menu]

  [[menu.main]]
  name = "About Me"
  weight = 300
  identifier = "about"
  url = "/about/about/"

  [[menu.main]]
  name = "CV"
  weight = 400
  identifier = "cv.pdf"
  url = "/cv/cv.pdf"
